### ISSUE TITLE
개발 진행 여부

### ISSUE THREAD

**Issue by jisungbin** [mooner1022/StarLight#19]
아직 프로젝트가 개발되고 있는 상태인가요?
20일동안 dev 브런치에 커밋이 없어 여쭤봅니다.

**Comment by mooner1022** [comment]
이번에 대학에 입학하며 기숙사에 가게 되어 여러모로 정신이 없었기에 커밋을 하지 못했습니다. 조만간 안정이 되고 나면 다시 개발 진행할 예정이며 개발이 중단된 것은 아닙니다.
