### ISSUE TITLE
메시지 2번 전송및 디버그룸 작동X

### ISSUE THREAD

**Issue by IntelPentium0** [mooner1022/StarLight#22]
![Screenshot_20230826-163856_StarLight](https://github.com/mooner1022/StarLight/assets/143253283/5a6158af-e0e5-46a9-8604-09c3d26c4881)

Starlight(이하 별빛으로 부르겠습니디)를 테스트 하는데 사용한 아주 간단한 소스 코드입니다.

![1693035526193](https://github.com/mooner1022/StarLight/assets/143253283/346d5580-20c4-4fad-bd93-a36058899601)
왜인지는 모르겠지만 자꾸 명령어를 수행할때 2번 메시지를 보냅니다.

다른방에서도 별빛 스크립트 태스트를 해보았지만 결과는 같았습니다.

![Screenshot_20230826-165526_StarLight](https://github.com/mooner1022/StarLight/assets/143253283/3e185183-2333-46b9-af29-826d0ea1f549)

그냥 제 폰이 문제인가 싶어서 별빛 내부 디버그룸에서 확인을 시도했지만 디버그룸은 그냥 먹통이더라구요...

**Comment by mooner1022** [comment]
간혹 안드로이드가 기존 알림 리스너를 종료하지 않고 새로운 리스너를 두 번 등록하는 현상이 발생하는데, 한 메세지에 두 번 답장하는 현상은 이것 때문으로 추정됩니다. 휴대폰을 한 번 재부팅해보시고, 이후에도 같은 현상이 계속된다면 말씀해주시겠어요?
디버그룸이 동작하지 않는 현상은 지금까지 진행했던 몇 번의 테스트 중엔 발견되지 않았던 현상인데, 이 부분은 제가 다시 한 번 확인해보겠습니다.

**Comment by mooner1022** [comment]
디버그룸이 동작하지 않는 현상에 관해서는 원인으로 추정되는 부분을 확인했으나, 현재 외출중이라 아마 오늘 밤중으로 수정된 빌드가 업데이트될 것 같습니다. 제보 감사합니다 🙂

추가) 디버그 룸에서 동작하지 않는 건 레거시 이벤트(response)뿐으로 보이니, 수정 전까진 기본 제공되는 onMessage 함수를 사용해보세요.
[매개변수 event 레퍼런스](https://gist.github.com/mooner1022/4473bc39241a9b4af6ebf44fb17a2f26)

**Comment by IntelPentium0** [comment]
> 디버그룸이 동작하지 않는 현상에 관해서는 원인으로 추정되는 부분을 확인했으나, 현재 외출중이라 아마 오늘 밤중으로 수정된 빌드가 업데이트될 것 같습니다. 제보 감사합니다 🙂
> 
> 추가) 디버그 룸에서 동작하지 않는 건 레거시 이벤트(response)뿐으로 보이니, 수정 전까진 기본 제공되는 onMessage 함수를 사용해보세요. [매개변수 event 레퍼런스](https://gist.github.com/mooner1022/4473bc39241a9b4af6ebf44fb17a2f26)

알겠습니다!! 빠른반영 감사합니다! :D

**Comment by mooner1022** [comment]
일단 디버그 룸에 관한 이슈는 수정하여 [배포중](https://cdn.discordapp.com/attachments/1106997962879545364/1145043952312004628/StarLight-0.1.0a-230827-release.apk)이니, 이벤트가 중복되어 수신되는 문제는 추가로 작성해주신 Issue에서 다루고 이 Issue는 닫도록 하겠습니다. #23
