### ISSUE TITLE
[Error]Api.replyRoom()

### ISSUE THREAD

**Issue by tmdgus0843** [mooner1022/StarLight#27]
사용한 코드 : `Api.replyRoom("Room", "TEST")`
에러 : 
`[JavaException]
java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
line : #2`

**Comment by mooner1022** [comment]
시간상 오늘 저녁 중으로 수정해서 배포될 듯 합니다. 제보 감사합니다.

**Comment by mooner1022** [comment]
2dbfdb068d2c9fd161ed6fb130ac12f268529d51 에서 수정되었습니다. 오늘 중으로 빌드본 배포될 예정입니다.
