### ISSUE TITLE
일정 프로젝트 개수 이상시 프로젝트가 보이지 않거나 특정 프로젝트가 두개 이상이 되는 문제

### ISSUE THREAD

**Issue by tmdgus0843** [mooner1022/StarLight#44]
안드로이드 11에 갤럭시 노트10, StarLight v0.2.1a-240209버전을 사용중입니다.
프로젝트의 개수가 일정수 이상이 되면 일부 프로젝트가 보이지 않거나 두개 이상으로 보여지는 문제가 있습니다.
재현 상황을 아래 링크로 첨부하였으니 확인 부탁드립니다.

[https://github.com/user-attachments/assets/cfb3488d-d051-495d-9c5d-c747e1f8b422](https://github.com/user-attachments/assets/cfb3488d-d051-495d-9c5d-c747e1f8b422)

**Comment by mooner1022** [comment]
0.3.0 업데이트 이후에도 발생하는지 확인 부탁드립니다

**Comment by seunghyun0934** [comment]
> 0.3.0 업데이트 이후에도 발생하는지 확인 부탁드립니다

V0.3.0a 업데이트 이후에는 해당 현상이 확인되지 않았습니다:)

**Comment by mooner1022** [comment]
그럼 일단 이슈는 닫겠습니다 😉 해당 이슈가 최신 버전에서 다시 발생한다면 이슈 다시 열어주세요
