### ISSUE TITLE
프로젝트 설정에서 값 수정후 저장버튼이 표시되지 않음

### ISSUE THREAD

**Issue by sampple-korea** [mooner1022/StarLight#45]
https://github.com/user-attachments/assets/931d34dd-3d06-4a10-ac4e-94a2ef31c3dd
https://github.com/user-attachments/assets/38469b8b-33dc-4d9b-bdcf-f850c7e75ea7

프로젝트를 설정후 저장버튼이 표시되지 않아 설정값을 저장할수 없습니다. 재시작후, 한번은 코드 최적화 설정을 조정하여 저장할 수 있지만 한번 저장후 앱재시작 전까지 버튼이 다시 나오지 않습니다. 

[오류 발생시 비활성화] 메뉴는 여러번 저장이 가능하지만, [코드 촤적화] 메뉴는 한번 저장하면 버튼이 다시 뜨지 않음.

앱 버전 : v0.3.0a-240814(build 4)
안드로이드 버전 : 14

**Comment by mooner1022** [comment]
0.3.1에서 수정됨, 해당 패치 커밋 후 close 예정

**Comment by mooner1022** [comment]
487058237715a475196d8f0a5d9806a047c126de 에서 수정되었습니다. 제보해주셔서 감사합니다 🙂
