### ISSUE TITLE
프로젝트 컴파일시 DEFAULT라 뜨는 현상

### ISSUE THREAD

**Issue by tmdgus0843** [mooner1022/StarLight#47]
안드로이드 11에 갤럭시 노트10, StarLight v0.3.0a-240814(build 4) 버전을 사용중입니다.
프로젝트를 컴파일하고 일정시간이 지나면 모든 프로젝트가 작동하지 않고 DEFAULT라 뜨며 컴파일이 되지 않는 현상이 있습니다.
재현 사진과 영상을 아래 링크로 첨부하였으니 확인 부탁드립니다.
![image](https://github.com/user-attachments/assets/cfbf8ab8-4733-429b-b4a8-cf3978fb7a2f)

 [video](https://github.com/user-attachments/assets/9288be47-60d9-4e7e-af8d-eb7de6494b39)

**Comment by seunghyun0934** [comment]
코드같은 경우는 문제로 추정되는 코드만 메일로 보내드리겠습니다.

**Comment by mooner1022** [comment]
넵 메일 확인했습니다

**Comment by mooner1022** [comment]
더 자세하게 확인해봐야 확실히 알겠지만, 일단 지금으로서는 `setTimeout`과 `setInterval`의 구현과 엮인 문제로 보입니다. 여러 방면으로 테스트해본 후 개선하여 배포하도록 하겠습니다. 제보 감사합니다.

이슈는 해결 커밋 푸시 전까지 열어 놓겠습니다. 추가적으로 말씀하실 사항이 있으시다면 이 곳에 추가해주시면 감사하겠습니다.

**Comment by seunghyun0934** [comment]
setInterval 외에도 KakaoLink 사용시 같은 현상이 발생하네요

**Comment by seunghyun0934** [comment]
> setInterval 외에도 KakaoLink 사용시 같은 현상이 발생하네요


KakaoLink가 한 번이상 작동하면 해당 프로젝트가 작동하지 않고, DEFAULT라 뜨는 현상이 있네요.

**Comment by mooner1022** [comment]
사용하신 카카오링크가 가장 최근에 배포된 카카오링크 라이브러리가 맞을까요?

**Comment by seunghyun0934** [comment]
> 사용하신 카카오링크가 가장 최근에 배포된 카카오링크 라이브러리가 맞을까요?

naijun0403님의 KakaoLink 2.0.0 beat3 버전을 사용하였습니다.
https://github.com/naijun0403/kakaolink/releases/tag/2.0.0-beta03

**Comment by mooner1022** [comment]
0a87dd7ff4be66454fad3caafe19b76a275fff8d 에서 수정되었(으면 좋겠)습니다

**Comment by jisungbin** [comment]
> [0a87dd7](https://github.com/mooner1022/StarLight/commit/0a87dd7ff4be66454fad3caafe19b76a275fff8d) 에서 수정되었(으면 좋겠)습니다

테스트 코드를 짜봅시다!
