### ISSUE TITLE
[BUG] V8 업데이트 안되는 문제

### ISSUE THREAD

**Issue by hahamini** [mooner1022/StarLight#55]
Document 보고 V8 을 설치했습니다.

도큐먼트 경로는 sdcard/StarLight/plugins/ 로 명시되어있지만, 

저는 sd카드가 없어서 내장 저장공간\/StarLight/plugins 에 저장했습니다.

재시작 후 플러그인 탭에 아무것도 없길래, 추가를 누르고 직접 경로에서 v8-arm64-release.slp 파일을 눌렀습니다.
"v8 로드 완료, 재시작시 적용됩니다" 라고 뜨고 재시작을 해도 바뀐게 없네요

아직 플러그인 없다고 뜨고, 새프로젝트에도 사용언어: 자바스크립트(RhinoJS) 만 나타납니다.

**Comment by mooner1022** [comment]
안녕하세요.

본 경우 플러그인이 제대로 호환되지 않고 있는 상황으로 보입니다.
문제 상황을 제대로 파악하기 위해, `로그` 탭에서 플러그인 로드 과정에서 에러나 경고가 발생하진 않았는지 확인 부탁드립니다.

문제가 보이지 않으신다면, 번거로우시겠지만 아래 과정을 통해 내부 로그 표시 기능 활성화 후 로그 내용을 첨부해주시면 감사하겠습니다.

1. `앱 설정 > 앱 정보 > 무너` 버튼을 연타하여 개발자 모드 활성화
2. 앱 재시작 (`앱 설정 > 일반 > 앱 재시작` 통해 완전 재시작)
3. 개발자 모드 > 내부 로그 표시 활성화
4. 앱 **완전 재시작** 후 앱 시작 과정에 발생한 로그 확인

아래는 올바르게 동작중인 플러그인의 로그 예시입니다.
![Screenshot_20241231_202601_StarLight.png](https://github.com/user-attachments/assets/d694cb80-3491-4fb0-abfc-5a87f08d8564)

**Comment by hahamini** [comment]
@mooner1022 

앱 설정 > 일반 > 앱 재시작 으로 하니 제대로 불러와집니다.

저는 안드로이드 백그라운드에서 닫기로 재시작 했었는데 그래서 안됐던거같네요

감사합니다

**Comment by hahamini** [comment]
@mooner1022 정말 죄송한데 라이노 코드와 호환이 안되네요.

에러는 `TypeError: onMessage is not a function` 입니다.

제가 어떤 코드를 보고 사용해야할지 몰라서 알려주시면 감사하겠습니다.
(함수정의 정도..?)

**Comment by mooner1022** [comment]
아마 [이곳](https://kbotdocs.dev/starlight/V8)의 문서를 보고 설치하신 것 같은데, 본 문서를 제가 작성하지 않은 관계로 일부 설명이 누락된 것 같습니다.

https://cafe.naver.com/nameyee/46214?tc=shared_link
위 글의 `주의사항` 항목을 참조하시면 될 것 같습니다.
이미지로도 첨부드리겠습니다.
![SmartSelect_20241231_220742_Naver Cafe.png](https://github.com/user-attachments/assets/d411e2a3-ff28-4de8-af38-a6c5cbdfc27f)

본 플러그인은 '챗봇의 개발에 V8 엔진의 성능을 활용할 수 있게 한다'가 목표인 플러그인으로, RhinoJS에 맞춰 작성된 코드와 상호 호환을 보장 또는 목표로 하지 않는 점 양해 부탁드립니다.

* 추가로, 원래의 issue와 관계 없거나 다른 주제인 질문은 추가적인 issue를 생성하여 질문하여 주세요.
